app/blueprints/ecommerce/models.py
from app import db

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.String, nullable=False)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    quantity = db.Column(db.Integer)

    def __repr__(self):
        return f'<Cart: {self.product_id} {self.user_id}>'

app/blueprints/ecommerce/__init__.py
from flask import Blueprint

bp = Blueprint('ecommerce', __name__, url_prefix='/shop')

from .import routes, models

app/blueprints/ecommerce/routes.py
from flask import flash, redirect, render_template, current_app, request, url_for
from flask_login import current_user
from app import db

from app.blueprints.ecommerce.models import Cart
from .import bp as app
import stripe
from app.context import cart_context

stripe.api_key = current_app.config.get('STRIPE_TEST_SECRET_KEY')

@app.route('/')
def products():
    # print(cart_context())
    # print(stripe.Product.list())
    products = [dict(
        id=p['id'],
        name=p['name'],
        description=p['description'],
        price=stripe.Price.retrieve(p['metadata']['price'])['unit_amount'] / 100,
        image=p['images'][0]
    ) for p in stripe.Product.list()['data']]
    # print(products)
    context = {
        'products': products
    }
    return render_template('ecommerce/products.html', **context)

@app.route('/products/add/<id>')
def add_product(id):
    # if the cart item exists inside of our cart_dict
    cart_item = Cart.query.filter_by(product_id=str(id)).filter_by(user_id=current_user.id).first()
    if cart_item:
        cart_item.quantity +=1
        db.session.commit()
    else:
        cart_item = Cart(product_id=str(id), user_id=current_user.id, quantity=1)
        db.session.add(cart_item)
        db.session.commit()
    flash(f'Product added to cart successfully', 'success')
    return redirect(url_for('ecommerce.products'))

@app.route('/products/cart')
def cart():
    cart_items = []
    for item in Cart.query.filter_by(user_id=current_user.id).all():
        stripe_product = stripe.Product.retrieve(item.product_id)
        product_dict = {
            'product': stripe_product,
            'price': stripe.Price.retrieve(stripe_product['metadata']['price'])['unit_amount'] / 100,
            'quantity': item.quantity
        }
        cart_items.append(product_dict)
    context = {
        'cart': cart_items
    }
    return render_template('ecommerce/cart.html', **context)

@app.route('/products/checkout', methods=['POST'])
def checkout():
    items = []
    for item in Cart.query.filter_by(user_id=current_user.id).all():
        stripe_product = stripe.Product.retrieve(item.product_id)
        product_dict = {
            'price': stripe.Price.retrieve(stripe_product['metadata']['price']),
            'quantity': item.quantity
        }
        items.append(product_dict)
    try:
        session = stripe.checkout.Session.create(
            line_items=items,
            mode='payment',
            success_url='http://localhost:5000/shop/products',
            cancel_url='http://localhost:5000/shop/products/checkout',
        )
    except Exception as error:
        return error

    # After successful payment, clear items from cart
    [db.session.delete(item) for item in Cart.query.filter_by(user_id=current_user.id).all()]
    db.session.commit()

    return redirect(session.url, code=303)

app/templates/ecommerce/cart.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <h3>
        Cart
        <span class="float-right">
            <form action="{{ url_for('ecommerce.checkout') }}" method="post">
                <input id="checkout-button" type="submit" class="btn btn-primary" value="Checkout">
            </form>
        </span>
    </h3>
    <hr>

    <div class="card shopping-cart">
        <div class="card-header bg-dark text-light">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            Shopping Cart
            <a href="" class="btn btn-outline-info btn-sm pull-right">Continue Shopping</a>
            <div class="clearfix"></div>
        </div>
        <div class="card-body">

            <!-- PRODUCT -->
            {% for p in cart %}
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-2 text-center">
                        <img class="img-responsive" src="{{ p.product.images[0] }}" alt="{{ p.product.name }}" height="80">
                    </div>
                    <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                        <h4 class="product-name"><strong>{{ p.product.name }}</strong></h4>
                        <h4>
                            <small>{{ p.product.description }}</small>
                        </h4>
                    </div>
                    <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                        <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                            <h6><strong>${{ '{:,.2f}'.format(p.price) }} <span class="text-muted">x</span></strong></h6>
                        </div>
                        <div class="col-4 col-sm-4 col-md-4">
                            <div class="quantity">
                                <input type="number" step="1" max="99" min="1" value="{{ p.quantity }}" title="Qty" class="qty" size="4">
                            </div>
                        </div>
                        <div class="col-2 col-sm-2 col-md-2 text-right">
                            <button type="button" class="btn btn-outline-danger btn-xs">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <hr>
            {% endfor %}
            <!-- END PRODUCT -->

            <div class="pull-right">
                <a href="" class="btn btn-outline-secondary pull-right">
                    Update Shopping Cart
                </a>
            </div>
        </div>
        <div class="card-footer">
            <!-- <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
                        <div class="row">
                            <div class="col-6">
                                <input type="text" class="form-control" placeholder="cupone code">
                            </div>
                            <div class="col-6">
                                <input type="submit" class="btn btn-default" value="Use cupone">
                            </div>
                        </div>
                    </div> -->
            <div class="text-right">
                <div class="cart-totals">
                    Grand total: <b>0.00</b>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

app/templates/ecommerce/products.html
{% extends 'layout.html' %}

{% block content %}

    <div class="row">
        {% for p in products %}
            <div class="card col-4">
                <img class="card-img-top" src="{{ p.image }}" alt="{{ p.name }}">
                <div class="card-body">
                    <h4 class="card-title">
                        {{ p.name }}
                        <span class="float-right">{{ '${}'.format(p.price) }}</span>
                    </h4>
                    <p class="card-text">{{ p.description }}</p>
                </div>
                <div class="card-footer">
                    <a href="{{ url_for('ecommerce.add_product', id=p.id) }}" class="btn btn-block btn-success">Add To Cart</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}