app/blueprints/authentication/models.py
from app import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    email = db.Column(db.String(100), unique=True)
    posts = db.relationship('Post', backref='user', lazy='dynamic')
    password = db.Column(db.String(255))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.generate_password(self.password)
        # self.password = generate_password_hash(self.password)

    def check_password(self, password_to_check):
        return check_password_hash(self.password, password_to_check)

    def generate_password(self, password_create_salt_from):
        self.password = generate_password_hash(password_create_salt_from)

    def to_dict(self):
        data = {
            'id': self.id,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'email': self.email
        }
        return data    

    def __repr__(self):
        return f'<User: {self.email}>'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/blueprints/authentication/__init__.py
from flask import Blueprint

bp = Blueprint('authentication', __name__, url_prefix='/auth')

from .import models, routes

app/blueprints/authentication/routes.py
from flask_login import current_user, login_user, logout_user
from .import bp as app
from flask import render_template, redirect, url_for, request, flash
from app.blueprints.authentication.models import User
from app import db

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email.lower()).first()
        if user is None or not user.check_password(password):
            flash('Either that was an invalid password or username. Try again. ', 'danger')
            return redirect(request.referrer)
        flash('User has successfully logged in', 'success')
        login_user(user)
        return redirect(url_for('blog.home'))
    return render_template('authentication/login.html')

    
@app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        data = request.form
        user = User.query.filter_by(email=data.get('email')).first()
        if user is not None:
            flash('That user already exists', 'warning')
            return redirect(request.referrer)
        if data.get('password') != data.get('password2'):
            flash("Your passwords don't match", 'warning')
            return redirect(request.referrer)
        new_user = User(
            first_name=data.get('first_name'),
            last_name=data.get('last_name'),
            email=data.get('email'),
            password=data.get('password')
        )
        db.session.add(new_user)
        db.session.commit()
        flash('User registered successfully', 'success')
        # automatically log in user on successful registration
        login_user(new_user)
        flash('User logged in successfully', 'success')
        return redirect(url_for('blog.home'))

    return render_template('authentication/register.html')

@app.route('/logout')
def logout():
    logout_user()
    flash('User logged out successfully', 'primary')
    return redirect(url_for('authentication.login'))

@app.route('/profile', methods=['GET', 'POST'])
def profile():
    if request.method == 'POST':
        # print(request.form)
        # print(current_user)
        data = request.form

        user = User.query.get(current_user.id)
        user.first_name = data.get('first_name')
        user.last_name = data.get('last_name')
        user.email = data.get('email')

        if (data.get('password') and data.get('password2')) and (data.get('password') == data.get('password2')):
            user.generate_password(data.get('password'))
        elif (data.get('password') or data.get('password2')):
            flash("Your passwords don't match", 'warning')
            return redirect(request.referrer)
        db.session.commit()
        flash('Your information has been updated', 'info')
        return redirect(request.referrer)
    context = {
        'posts': current_user.posts.all()
    }
    return render_template('authentication/profile.html', **context)

app/templates/authentication/login.html
{% extends 'layout.html' %}

{% block content %}
<h1>Login</h1>

<hr>

<form action="{{ url_for('authentication.login') }}" method="POST">

    <div class="form-group">
        <input type="email" class="form-control" name="email" placeholder="Email" />
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="Password" />
    </div>
    <input type="submit" value="Login" class="btn btn-info btn-block" />

</form>
{% endblock %}

app/templates/authentication/profile.html
{% extends 'layout.html' %}

{% block content %}
<h1>Profile</h1>

<hr>

<div class="row">
    <div class="col-6">
        <img src="https://via.placeholder.com/700x700" class="img-fluid" alt="">
    </div>
    <div class="col-6">
        <form action="{{ url_for('authentication.profile') }}" method="POST">
        
            <div class="form-group">
                <input type="text" class="form-control" value="{{ current_user.first_name }}" name="first_name" placeholder="First Name" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" value="{{ current_user.last_name }}" name="last_name" placeholder="Last Name" />
            </div>
            <div class="form-group">
                <input type="email" class="form-control" value="{{ current_user.email }}" name="email" placeholder="Email" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password2" placeholder="Confirm Password" />
            </div>
            <input type="submit" value="Update" class="btn btn-info btn-block" />
        
        </form>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-12">
        
        {% for post in posts %}
        <li class="list-group-item unique-list profile-posts">
            <p>
                <a href="{{ url_for('blog.blog_single', id=post.id) }}">
                    {{ post.body }}
                </a>
                <span class="float-right">
                    <small>{{ moment(post.date_created).fromNow() }}</small>
                </span>
            </p>
            <cite>
                <!-- can access data being passed into a template using either dot notation, or literal notation -->
                &mdash; {{ post.user.first_name }} {{ post.user.last_name }}
                {# &mdash; {{ user['first_name'] }} {{ user['last_name'] }} #}
            </cite>
        </li>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/authentication/register.html
{% extends 'layout.html' %}

{% block content %}
<h1>Register</h1>

<hr>
<form action="{{ url_for('authentication.register') }}" method="POST">

    <div class="form-group">
        <input type="text" class="form-control" name="first_name" placeholder="First Name" />
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="last_name" placeholder="Last Name" />
    </div>
    <div class="form-group">
        <input type="email" class="form-control" name="email" placeholder="Email" />
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="Password" />
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="Confirm Password" />
    </div>
    <input type="submit" value="Register" class="btn btn-info btn-block" />

</form>
{% endblock %}